/**
 * Model registry — the single source of truth for which model ids KiroLink
 * accepts and advertises.
 *
 * Previously the /v1/models response was generated by a family x version
 * cartesian product inside the HTTP router, while the validation pattern and
 * the non-Claude allowlist lived in the translator, with the two lists kept in
 * sync by a comment. Every Claude release meant editing the router.
 */

/** Claude families Kiro serves. */
const CLAUDE_FAMILIES = ['claude-opus', 'claude-sonnet', 'claude-haiku'] as const

/**
 * Claude versions Kiro currently accepts, canonical dotted form. Clients also
 * send the dashed form (4-6) and a [1m] long-context suffix; both are
 * normalized to these by `normalizeModelId`.
 */
const CLAUDE_VERSIONS = ['4', '4.5', '4.6', '4.7', '4.8'] as const

/**
 * Dated aliases clients send verbatim. The date suffix is stripped during
 * normalization, so these exist only so /v1/models advertises them.
 */
const DATED_ALIASES = [
  'claude-opus-4-20250514',
  'claude-sonnet-4-20250514',
  'claude-haiku-4-20250414',
  'claude-sonnet-4.5-20250620',
  'claude-opus-4.5-20250620',
  'claude-sonnet-4-6-20260601',
  'claude-opus-4-6-20260601',
  'claude-sonnet-4-8-20260611',
  'claude-opus-4-8-20260611',
] as const

/**
 * Non-Claude models Kiro exposes via `kiro-cli chat --list-models`, verified
 * live against the runtime. `glm-5` and `deepseek-3.2` are listed there too but
 * the runtime rejects them ("Invalid model ID") — keep them out until Kiro's
 * own model list catches up, so a client fails fast here with a clear
 * "unsupported model" error instead of failing upstream.
 */
export const NON_CLAUDE_MODEL_IDS: ReadonlySet<string> = new Set([
  'auto',
  'minimax-m2.5',
  'minimax-m2.1',
  'qwen3-coder-next',
])

const CLAUDE_MODEL_PATTERN = /^claude-(?:opus|sonnet|haiku)-\d+(?:\.\d+)?$/u

export type ModelDescriptor = {
  id: string
  object: 'model'
  owned_by: string
  modalities: { input: string[]; output: string[] }
  capabilities: { vision: boolean; image: boolean }
}

/**
 * Normalize a client-supplied model id to the canonical id Kiro expects.
 * Returns undefined when the model is not supported.
 */
export function normalizeModelId(model: string): string | undefined {
  if (NON_CLAUDE_MODEL_IDS.has(model)) return model
  const id = model
    .replace(/\[1m\]$/u, '')
    .replace(/-\d{8}$/u, '')
    .replace(/^(claude-(?:opus|sonnet|haiku)-\d+)-(\d+)$/u, '$1.$2')
  return CLAUDE_MODEL_PATTERN.test(id) ? id : undefined
}

/** The /v1/models payload. */
export function listModels(): { object: 'list'; data: ModelDescriptor[] } {
  const claude: ModelDescriptor[] = []
  for (const family of CLAUDE_FAMILIES) {
    for (const version of CLAUDE_VERSIONS) {
      // Clients send both dotted and dashed forms; advertise both, plus the
      // [1m] long-context variant of each.
      for (const id of [`${family}-${version}`, `${family}-${version.replace('.', '-')}`]) {
        claude.push(claudeDescriptor(id))
        claude.push(claudeDescriptor(`${id}[1m]`))
      }
    }
  }
  for (const id of DATED_ALIASES) claude.push(claudeDescriptor(id))

  const nonClaude = [...NON_CLAUDE_MODEL_IDS].map((id): ModelDescriptor => ({
    id,
    object: 'model',
    owned_by: 'kiro',
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { vision: false, image: false },
  }))

  return { object: 'list', data: dedupeById([...claude, ...nonClaude]) }
}

function claudeDescriptor(id: string): ModelDescriptor {
  return {
    id,
    object: 'model',
    owned_by: 'anthropic',
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: { vision: true, image: true },
  }
}

function dedupeById(models: ModelDescriptor[]): ModelDescriptor[] {
  const seen = new Set<string>()
  const out: ModelDescriptor[] = []
  for (const model of models) {
    if (seen.has(model.id)) continue
    seen.add(model.id)
    out.push(model)
  }
  return out
}
